# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# Disable emulator audio
machine:
  environment:
    QEMU_AUDIO_DRV: none

dependencies:
  docker:
    - image: circleci/android:api-25-alpha
  pre:
    - unset ANDROID_NDK_HOME
    - ./gradlew dependencies

test:
  override:
    - unset ANDROID_NDK_HOME
    - emulator -avd circleci-android24 -no-audio -no-window:
        background: true
        parallel: true
    - circle-android wait-for-boot
    - ./gradlew test
    - ./gradlew connectedAndroidTest